---
title: The SUBSTATION
timezone: Australia/Melbourne
collections:
  about:
    title: About Us
    output: true
  posts:
    title: Events
    output: true
  residents:
    title: Residents
    output: true
  supporters:
    title: Supporters
    output: false
  uploads:
    title: Uploads
    output: false
  venues:
    title: Venues
    output: true
defaults:
- scope:
    path: ''
    type: about
  values:
    layout: post
    permalink: "/:collection/:path/"
- scope:
    path: ''
    type: residents
  values:
    layout: post
    permalink: "/:collection/:path/"
- scope:
    path: ''
    type: venues
  values:
    layout: post
    permalink: "/:collection/:path/"
    venue-cta: true
- scope:
    path: ''
    type: pages
  values:
    layout: post
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:categories/:title/"
    title: 
    categories: 
    image: 
    image-credit: 
    video: 
    button-url: 
    button-txt: 
    presented-by: false
    price: false
    dates: 
    has-opening-event: false
    has-preview-event: false
    has-closing-event: false
    has-start-time: false
    has-mins: false
    is-single-date: false
    is-list-of-dates: false
    is-opening-hours-time: false
    is-single-time-duration: false
    is-single-month-duration: false
    is-months-duration: false
    event-duration-txt: 
    notes: false
    supporters: 
description: The SUBSTATION is a unique large-scale multi-purpose gallery, performance
  space and dance studio for artists of every kind, in Newport, Melbourne, Australia.
baseurl: 
url: http://thesubstation.org.au
logo: "/uploads/the-substation-logo.png"
facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234
  username: TheSubstationNewport
twitter:
  username: thesubstation_
social:
  name: The SUBSTATION
  links:
  - https://www.facebook.com/TheSubstationNewport/
  - https://www.instagram.com/thesubstation/
  - https://twitter.com/thesubstation_
author: patternworks_
address: 1 Market Street, Newport
address-second: Victoria 3015, Australia
address-link: https://goo.gl/maps/3RTKiR89iD72
phone: "(03) 9391 1110"
email: info@thesubstation.org.au
email-events: events@thesubstation.org.au
gallery-hours: Tues–Sat, 11am–5pm
office-hours: Tues–Fri, 9am–5pm
events-manager: Marisa Fiume
google-analytics: UA-79358718-1
imageurl: "/assets/images/"
uploadurl: "/uploads/"
javascriptsurl: "/assets/javascripts/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
exclude:
- assets/_source
- Gemfile
- Gemfile.lock
- ".gitignore"
- editorconfig
- gulpfile.js
- package.json
- node_modules
- yarn.lock
- DESCRIPTION*
- README*
- TODO*
