---
title: The SUBSTATION
timezone: Australia/Melbourne
collections:
  about:
    title: About Us
    output: true
  posts:
    title: Posts
    output: true
  residents:
    title: Residents
    output: true
  supporters:
    title: Supporters
    output: false
  uploads:
    title: Uploads
    output: false
  venues:
    title: Venues
    output: true
defaults:
- scope:
    path: ''
    type: about
  values:
    layout: post
    permalink: "/:collection/:path/"
- scope:
    path: ''
    type: residents
  values:
    layout: post
    permalink: "/:collection/:path/"
- scope:
    path: ''
    type: venues
  values:
    layout: post
    permalink: "/:collection/:path/"
- scope:
    path: ''
    type: pages
  values:
    layout: post
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:categories/:title/"
    title:
    categories:
    image:
    image-credit:
    video:
    buy-url:
    buy-button-txt:
    presented-by: false
    price: false
    dates:
    has-opening-event: false
    has-preview-event: false
    has-closing-event: false
    has-start-time: false
    date-is-single: false
    dates-is-list: false
    time-is-opening-hours: false
    time-is-single: false
    time-is-month: false
    time-is-months: false
    time-has-mins: false
    event-duration-txt:
    notes: false
    supporters:
    -
description: |
    Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search   results) and in your feed.xml site description.
baseurl:
url: http://thesubstation.org.au
logo: "/uploads/the-substation-logo.png"
address: 1 Market Street Newport VIC 3015
address-link: https://goo.gl/maps/3RTKiR89iD72
phone: "(03) 9391 1110"
email: info@thesubstation.org.au
gallery-hours: Tuesday to Saturday 11am–5pm
office-hours: Tuesday to Friday 9am–5pm
google-analytics:
imageurl: "/assets/images/"
javascriptsurl: "/assets/javascripts/"
uploadurl: "/uploads/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
exclude:
- assets/_source
- Gemfile
- Gemfile.lock
- editorconfig
- gulpfile.js
- package.json
- node_modules
- yarn.lock
- README.md
- TODO.md
